### ISSUE TITLE
RowCoder not equal after serialization

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19163]
The following code throws an exception:

```

import org.apache.beam.sdk.coders._
import org.apache.beam.sdk.schemas.Schema

val schema =
  
   Schema
        .builder()
        .addInt32Field("c1")
        .addStringField("c2")
       
.addDoubleField("c3")
        .build()

val coder = RowCoder.of(schema)
org.apache.beam.sdk.util.SerializableUtils.ensureSerializable(coder)

```

```

java.lang.IllegalStateException: Coder not equal to original after serialization, indicating that the
Coder may not implement serialization correctly.  Before: org.apache.beam.sdk.coders.RowCoder@1323050e,
after: org.apache.beam.sdk.coders.RowCoder@4c03150a

```

Imported from Jira [BEAM-5645](https://issues.apache.org/jira/browse/BEAM-5645). Original Jira may contain additional context.
Reported by: jto.

**Comment by RustedBones** [comment]
This bug is not relevant anymore. `RowCoder` does now implement proper [equality](https://github.com/apache/beam/blob/e62ae391985fc13c7df1ee6e088525835ceaa560/sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoder.java#L53) since this [commit](https://github.com/apache/beam/commit/e14f3f84ba0da6288db4795b92199e2905134a17#diff-cee7966ac7d79d0b225c1b25b538f1e7c2784206b9d6d3a15234d887a3963b9a)

**Comment by kennknowles** [comment]
Thanks for the update!
