### ISSUE TITLE
AttributeError: 'SubscriberClient' object has no attribute 'transport' error while reading from input subscription with ReadFromPubSub

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20564]
When I read from the input-subcroption with beam.io.ReadFromPubSub. The error below is thrown.
>  AttributeError: 'SubscriberClient' object has no attribute 'transport'
>  

Code

`pipeline_options = PipelineOptions()`
`pipeline_options.view_as(StandardOptions).streaming = True`

`pipeline = beam.Pipeline(options=pipeline_options)`
`messages = (pipeline | beam.io.ReadFromPubSub(subscription=input_subscription).with_output_types(bytes))`

`def printattr(element):`
` print(element.attributes)`

`lines = messages | 'printattr' >> beam.Map(printattr)`

`result = pipeline.run()`
`result.wait_until_finish()`

Imported from Jira [BEAM-11318](https://issues.apache.org/jira/browse/BEAM-11318). Original Jira may contain additional context.
Reported by: celine.

**Comment by kennknowles** [comment]
@johnjcasey @tvalentyn this should be easy to validate or not; I assume reading from Pubsub does work with Python, but is there a corner case? it probably changed a lot since this issue

**Comment by tvalentyn** [comment]
Please reopen if you still the issue and provide a complete example. The above example wouldn't work since the pubsub message is not properly decoded, see example in https://github.com/apache/beam/blob/ec91ea4f6b83e6a8e3bd2041057fa90d0c8f0dd0/sdks/python/apache_beam/examples/inference/online_clustering/clustering_pipeline/main.py#L108
