### ISSUE TITLE
Dataflow runner v2 tests occasionally fails with misconfigured sharding logic

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20806]
Dataflow runner v2 test sometimes mysteriously fails data loss error message. This is due to misconfigured sharding logic from backend with combination of shuffle_mode=service and use_runner_v2 logic.

Example failing pipeline: https://pantheon.corp.google.com/dataflow/jobs/us-central1/2021-02-08_10_20_51-4474446822883759937?project=apache-beam-testing

Imported from Jira [BEAM-11779](https://issues.apache.org/jira/browse/BEAM-11779). Original Jira may contain additional context.
Reported by: yichi.

**Comment by Abacn** [comment]
Is this issue still present? Working on #24633 and find the performance decrease when adding ReShuffle is due to `shuffle_mode=appliance` option added. The original BEAM-11779 has multiple linked PRs, all but one are adding `shuffle_mode=appliance` option to test; the last one (#15316) removed this option in go test, commenting "The issue should be resolved." but not others.

**Comment by damccorm** [comment]
@lostluck @lukecwik who may have context since they were on #15316

**Comment by lukecwik** [comment]
This is tracking http://b/179694817 and had rolled out to prod in Q1 2021. I believe it is resolved but pinged @tudorm for confirmation.
