### ISSUE TITLE
Allow skipping of any output when writing an empty PCollection.

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21608]
I've seen this request come up a few times, e.g. https://stackoverflow.com/questions/72126198/how-can-we-prevent-empty-file-write-in-dataflow-pipeline-when-collection-size-is

Imported from Jira [BEAM-14426](https://issues.apache.org/jira/browse/BEAM-14426). Original Jira may contain additional context.
Reported by: robertwb.

**Comment by tiwarinaman** [comment]
I saw that in the new version (2.40.0) there is a new method called **skipIfEmpty()** which is available in the **writeCustomType()** implementation as you can see in the below code

```java
errorRecords.apply("WritingErrorRecords", TextIO.<String>writeCustomType().to(options.getBucketPath())
             .withHeader("ID|ERROR_CODE|ERROR_MESSAGE")
             .skipIfEmpty()
             .withoutSharding()
             .withSuffix(".txt")
             .withShardNameTemplate("-SSS")
             .withNumShards(1));
  ```

This code will work when the PCollection is empty which is good this is what we wanted but when PCollection is not empty then It will throw NullPointerException pasted below.

```java
Exception in thread "main" org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.NullPointerException: Cannot invoke "org.apache.beam.sdk.transforms.SerializableFunction.apply(Object)" because "this.formatFunction" is null
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:373)
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:341)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:218)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:67)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:323)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:309)
	at org.apache.beam.examples.WordCount.runWordCount(WordCount.java:97)
	at org.apache.beam.examples.WordCount.main(WordCount.java:113)
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.beam.sdk.transforms.SerializableFunction.apply(Object)" because "this.formatFunction" is null
	at org.apache.beam.sdk.io.DynamicFileDestinations$ConstantFilenamePolicy.formatRecord(DynamicFileDestinations.java:51)
	at org.apache.beam.sdk.io.WriteFiles$WriteShardsIntoTempFilesFn.processElement(WriteFiles.java:953)
```

I believe this is because when we build the object of **AutoValue_TextIO_TypedWrite** so in the setter of **DynamicDestinations** initially it's null and we never update the value. 
I'm talking about the below apache beam code in TextIO file.

```java
public static <UserT> TypedWrite<UserT, Void> writeCustomType() {
        return (new AutoValue_TextIO_TypedWrite.Builder()).setFilenamePrefix((ValueProvider)null).setTempDirectory((ValueProvider)null).setShardTemplate((String)null).setFilenameSuffix((String)null).setFilenamePolicy((FileBasedSink.FilenamePolicy)null).setDynamicDestinations((FileBasedSink.DynamicDestinations)null).setDelimiter(new char[]{'\n'}).setWritableByteChannelFactory(org.apache.beam.sdk.io.FileBasedSink.CompressionType.UNCOMPRESSED).setWindowedWrites(false).setNoSpilling(false).setSkipIfEmpty(false).build();
    }
```

So can somebody help me to solve this problem actually I'm working on a project and this issue is on **priority**.

**Comment by Abacn** [comment]
@tiwarinaman  Looks like the cause is that formatFunction is not set automatically in writeCustomType. Does it raise the same error if not setting skipIfEmpty?

TextIO.write also supports skipIfEmpty and it sets formatFunction in its to() method. For writeCustomType you may need to manually set formatFunction. 

Indeed, documentation needs to be improved.

**Comment by tiwarinaman** [comment]
@Abacn Yeah I tried to use **writeCustomType()** without **skipIfEmpty()** but getting same error as before.

Even I tried to use **TextIO.write** but I can't find **skipIfEmpty** method can you help me with a code snippet?

And what to set in formatFunction ?

**Comment by Abacn** [comment]
@tiwarinaman There is a code snippet og skipIfEmpty() in unit tests. Here a write transform is constructed using `TextIO.write().to()`

https://github.com/apache/beam/blob/54b0784da7ccba738deff22bd83fbc374ad21d2e/sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOWriteTest.java#L394

**Comment by tiwarinaman** [comment]
@Abacn Thanks for your support, my problem is solved :)

**Comment by tvalentyn** [comment]
@Abacn is there anything left to do regarding doc improvements (see https://github.com/apache/beam/issues/21608#issuecomment-1192799831)?

**Comment by Abacn** [comment]
ah, I already lost the context for that comment. A documentation improvement is mention that `For writeCustomType you may need to manually set formatFunction.`
