### ISSUE TITLE
[Task]: Implement Timers

### ISSUE THREAD

**Issue by damccorm** [apache/beam#22737]
### What needs to happen?

Part of https://github.com/apache/beam/issues/20510 - designed here - https://docs.google.com/document/d/1rcKa1Z6orDDFr1l8t6NA1eLl6zanQbYAEiAqk39NQUU/edit?usp=sharing

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-go

**Comment by damccorm** [comment]
@riteshghorse I split state and timers into 2 issues to make public tracking a little easier (I'm planning on adding a bunch of subissues for State as well). Could you self-assign this one by commenting `.take-issue`?

**Comment by riteshghorse** [comment]
SGTM, thanks

**Comment by riteshghorse** [comment]
.take-issue

**Comment by lostluck** [comment]
Timers are now added complete, so marking this as complete.

We do need to add them to the Programming guide, but we can update the site that closer to the 2.48.0 release.

**Comment by lostluck** [comment]
Closing this after I finish my cleanup pass (and adding the CHANGES.md).

**Comment by lostluck** [comment]
Looks like there's a bit more work to do on the execution side, WRT timers that loop & can be processed immeadiately due to various firing delays...
 https://github.com/apache/beam/blob/f154d0165d31068f9e0d2ae008d7823dcf4cf53a/sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java#L1667

**Comment by riteshghorse** [comment]
Moving this to 2.49 due to the remaining cleanup
