### ISSUE TITLE
[Bug]: Importing bigquery_schema_tools.py needed to utilize read_gbq.

### ISSUE THREAD

**Issue by svetakvsundhar** [apache/beam#23760]
### What happened?

When utilizing `apache_beam.dataframe.io.read_gbq`, we see an error as described in the image.
<img width="1205" alt="Screen Shot 2022-10-19 at 1 13 11 PM" src="https://user-images.githubusercontent.com/26037657/197025025-574be904-e2fc-4511-b986-9a5a04599d1d.png">

A workaround to this is to add `from apache_beam.io.gcp import bigquery_schema_tools` to the Python file that calls`read_gbq`. 

### Issue Priority

Priority: 2

### Issue Component

Component: dsl-dataframe

**Comment by svetakvsundhar** [comment]
.take-issue

**Comment by TheNeuralBit** [comment]
### What went wrong?

The issue here is that we were accessing the `apache_beam.io.gcp.bigquery_schema_tools` package through the overall `beam` import (i.e. accessing  `import beam; beam.io.gcp.bigquery_schema_tools`), rather than importing it directly as we typically do (i.e. `from apache_beam.io.gcp import bigquery_schema_tools`) . Unfortunately it seems the bigquery_schema_tools package is not defined until it is imported specifically _somewhere_ in the program. So if we try to access `beam.io.gcp.bigquery_schema_tools` before that point, you'll get an error. 

### Why didn't tests catch this?
We do have tests for this in [apache_beam.dataframe.io_it_test]( https://github.com/apache/beam/blob/master/sdks/python/apache_beam/dataframe/io_it_test.py). I'm not quite sure why they didn't catch this - presumably the package is imported somewhere else in the course of running tests, either in another test, or during discovery. So the attribute access works in that context.

**Comment by svetakvsundhar** [comment]
> ### Why didn't tests catch this?
> We do have tests for this in [`apache_beam.dataframe.io_it_test`](https://github.com/apache/beam/blob/master/sdks/python/apache_beam/dataframe/io_it_test.py). I'm not quite sure why they didn't catch this - presumably the package is imported somewhere else in the course of running tests, either in another test, or during discovery. So the attribute access works in that context.

-I agree with this reasoning. I ran an experiment on the test file removing the `apache_beam.io.gcp.bigquery_schema_tools` import, and the error surfaced on the IDE.
