### ISSUE TITLE
[Task]: Remove Avro dependency from "sdks/java/core"

### ISSUE THREAD

**Issue by aromanenko-dev** [apache/beam#24292]
### What needs to happen?

Beam Java SDK still depends on the rather old version of Avro (1.8.2) whereas the latest version of Avro is 1.11.0 for the moment (Avro 1.11.1 is coming soon). Unfortunately, Avro 1.8.2 dependency brings several CVEs, though the latest Avro 1.11.0 brings only one.

Several attempts to bump Beam Avro dependency to more recent ones have been done in the past but all of them were not successful because of different reasons. Mostly, because this update with introduce some incompatible changes that Avro made between the versions and this may affect directly the Beam users and, potentially, it may affect the transitive dependencies while using Beam with other projects that use Avro as well.

It was decided to copy all Java Avro-related code from `sdks/java/core` to a dedicated extension, deprecate old code and finally remove it. 

More details can be found here:
https://lists.apache.org/thread/47oz1mlwj0orvo1458v5pw5c20bwt08q

- [x] #24293 
- [x] #24748
- [x] #25215
- [x] #24749
- [x] #25252
- [x] #24798

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-avro

**Comment by mosche** [comment]
Do you want to add a subtask to update https://beam.apache.org/documentation/io/connectors/?

**Comment by aromanenko-dev** [comment]
@mosche Good point, added. Thanks!

**Comment by therealdorin** [comment]
Hello @aromanenko-dev , according your documentation a logical type Date should be mapped to DATE type, but in the code below (line 1023) why is it mapped to DATETIME, since DATETIME and DATE are different types. The wrong mapping causes a problem when trying to ingest data into BigQuery. Is there a explanation or just a mismatch? 

https://github.com/apache/beam/blame/070a41e950cd590c7c37159af49b00bfe7e1a14d/sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/schemas/utils/AvroUtils.java#L1023C22-L1023C23

**Comment by aromanenko-dev** [comment]
@therealdorin 
Well, it was almost 3 years ago, so I can forget something but iinm, there is no `FieldType.DATE` in Beam schema - so I used `FieldType.DATETIME` for all date/time Avro types.
