### ISSUE TITLE
[Failing Test]: beam_PreCommit_PythonDocs_Cron 

### ISSUE THREAD

**Issue by kileys** [apache/beam#24976]
### What happened?

Last 5 runs are failing 
https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by kileys** [comment]
@damccorm

**Comment by damccorm** [comment]
Comparing the last successful run and the first failing run, there aren't many differences. The dependencies installed are the same, and there are no code changes.

The only meaningful changes I can find in the output is that this line appears in the logs in the failing run:

```
	WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://googleapis.dev/python/datastore/latest/objects.inv' not readable due to ValueError: unknown or unsupported inventory version: ValueError('invalid inventory header: <!doctype html>')
```

In the past this has been caused by docs moving - https://issues.apache.org/jira/browse/BEAM-13848?jql=project%20%3D%20BEAM%20AND%20text%20~%20%22unknown%20or%20unsupported%20inventory%20version%22%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC - at a glance, that doesn't seem to be the case:
 https://github.com/apache/beam/blob/5cc5b196a40d91a2b878ea30da6f3af1410c3c85/sdks/python/scripts/generate_pydoc.sh#L145

leads to https://googleapis.dev/python/datastore/latest/ which at least redirects to https://cloud.google.com/python/docs/reference/datastore/latest/index.html
