### ISSUE TITLE
[Feature Request]: SDK process termination bypasses Fn Logging API

### ISSUE THREAD

**Issue by cozos** [apache/beam#25314]
### What would you like to happen?

When the language-specific SDK process terminates, the boot.go harness will simply log out the `ExitError`:

* https://github.com/apache/beam/blob/679d30256c6bd64d9760702c667d7d355e70166b/sdks/go/container/boot.go#L169
* https://github.com/apache/beam/blob/679d30256c6bd64d9760702c667d7d355e70166b/sdks/java/container/boot.go#L236
* https://github.com/apache/beam/blob/679d30256c6bd64d9760702c667d7d355e70166b/sdks/python/container/boot.go#L265
* https://github.com/apache/beam/blob/679d30256c6bd64d9760702c667d7d355e70166b/sdks/typescript/container/boot.go#L179

These logs are important - you would imagine that the user would want to know if their process was terminated due to things like segfaults, panics or OOM killer SIGKILL.  

However, these logs do NOT go through the Fn Logging API and therefore does not have any important annotations - like the portability worker id and severity (i.e. `INFO`, `FATAL`). 

In Cloud Dataflow, this makes the important process termination logs show up in `worker-startup` with `INFO` severity:
![bad_c++_logs copy](https://user-images.githubusercontent.com/2646862/216745756-1ac737f3-794a-4da5-a33d-3b4575f9d117.png)

Instead, I think that these process termination logs should be formatted into the Fn API [LogEntry](https://github.com/apache/beam/blob/14e8de6e99a031ba7376bdb6837d471648878932/model/fn-execution/src/main/proto/org/apache/beam/model/fn_execution/v1/beam_fn_api.proto#L996) protobuf message and sent to the Fn Logging API.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [X] Component: Python SDK
- [X] Component: Java SDK
- [X] Component: Go SDK
- [X] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

**Comment by lostluck** [comment]
Due to the way the container contract operates, the logging on termination has no meaningful threadID, step ID etc. Fatalf was used because the SDK harness should never be exiting normally. It'd be up to the runner to manager the logging service to elide any noise from a normally terminating job (eg. due to successful completion, or due to repeated bundle failures).

Basically, the "thread, step etc" ids aren't useful in debugging since it's noting that a separate process crashed, and it's not intended to try and recover at this level. It needs to log the failure, and exit out.

It would have a meaningful worker ID however which could lead to debugging WRT profiling and similar (at least on the Dataflow UI).

**Comment by cozos** [comment]
Thanks so much!
