### ISSUE TITLE
[Bug]: go pipeline breaks after update to 2.48.0

### ISSUE THREAD

**Issue by FranciscoKurpiel** [apache/beam#27064]
### What happened?

After deploying to Dataflow a pipeline written in go, the workers crash immediately with:

```
Workflow failed. Causes: Job appears to be stuck. Several workers have failed to start up in a row, and no worker has successfully started up for this job. Last error reported: Unable to pull container image due to error: image pull request failed with error: Error response from daemon: manifest for apache/beam_go_sdk:2.48.0.dev not found: manifest unknown: manifest unknown. This is likely due to an invalid SDK container image URL. Please verify any provided SDK container image is valid and that Dataflow workers have permissions to pull image..
```

Looks like the `.dev` shouldn't be there.

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
The 2.48.0 tag still has .dev suffix:

https://github.com/apache/beam/blob/v2.48.0/sdks/go/pkg/beam/core/core.go#L30

while 2.47.0 and others does not:

https://github.com/apache/beam/blob/v2.47.0/sdks/go/pkg/beam/core/core.go#L30

Python version has same issue:

https://github.com/apache/beam/blob/v2.48.0/sdks/python/apache_beam/version.py#L20

Some step was missing in release process

CC: @riteshghorse @jrmccluskey

**Comment by Abacn** [comment]
Confirm that the released go sdk version is not correct:

```
$ cd ~/go/pkg/mod/github.com/apache/beam/sdks/v2@v2.48.0/go/pkg/beam/core
$ cat core.go
...
	SdkVersion = "2.48.0.dev"
```

**Comment by Abacn** [comment]
For python, unzip the released py source (https://pypi.org/project/apache-beam/2.48.0/#files) the version number is correct though.

We need to redo the release of go sdk

**Comment by jrmccluskey** [comment]
The tagged commit for 2.48.0 on the open source side is not correct, which is what is causing the issue. The commit history for the final version tag (https://github.com/apache/beam/commits/v2.48.0) is the same as the history for RC1 (https://github.com/apache/beam/commits/v2.48.0-RC1) apart from the version setting commit. It lacks RC2 changes and the version setting commit (https://github.com/apache/beam/commits/v2.48.0-RC2). 

Deleting the incorrect tag and then tagging the correct commit (https://beam.apache.org/contribute/release-guide/#git-tag) should fix the Go release since that versioning is pulled automatically. The 2.48.0 release will also need to be updated to the new tag on GitHub.

**Comment by Abacn** [comment]
Thanks @jrmccluskey for the investigation. So this only affects v2.48.0 tag in GitHub (which is where go sdk is installed) would you mind re-tag the release? Thanks!

**Comment by lostluck** [comment]
We'll need to add a `sdks/v2.48.1` tag to fix this for the Go SDK, since by the nature of Go Module releases, they are not fixable by "moving" the tag. Basically, the distributed Go Release infra has already cached the bad version.

IMHO doing a "patch" release for just the Go SDK isn't the end of the world, because Beam doesn't do Patch releases anyway. And since Go already has it's own version tag, this is non-invasive to other SDKs.

We would still keep the "SDKVersion" in core/core.go as 2.48.0 however, since we aren't rebuilding container images for this, and nor should we.

**Comment by lostluck** [comment]
Note that the constant is correct in both RCs

https://pkg.go.dev/github.com/apache/beam/sdks/v2@v2.48.0-RC1/go/pkg/beam/core

https://pkg.go.dev/github.com/apache/beam/sdks/v2@v2.48.0-RC2/go/pkg/beam/core

But incorrect in the released version: https://pkg.go.dev/github.com/apache/beam/sdks/v2@v2.48.0/go/pkg/beam/core

And that the cached tag is dated earlier for v2.48.0:
https://pkg.go.dev/github.com/apache/beam/sdks/v2@v2.48.0/go/pkg/beam/core?tab=versions

**Comment by jrmccluskey** [comment]
Quick addendum to this, the version will be at tag `sdks/v2.48.2` as there were still some issues with Ritesh's environment and the Go tooling picked it up before we could correct it

**Comment by jrmccluskey** [comment]
@FranciscoKurpiel version 2.48.2 is now live (https://pkg.go.dev/github.com/apache/beam/sdks/v2@v2.48.2/go) so you should be ready to go! Let us know if there's another issue that comes up, either by re-opening this ticket or filing a new one. Thank you for bringing this to our attention!

**Comment by FranciscoKurpiel** [comment]
Fix validated on my side. Thank you for the quick fix.
