### ISSUE TITLE
[Feature Request]: Support Java 21

### ISSUE THREAD

**Issue by deathstarjanitor** [apache/beam#28120]
### What would you like to happen?

Java 21 is expected to release in September, 2023.
https://www.java.com/releases/matrix/

Beam should support building Java pipelines using the Java 21 SDK.
Beam should also support running on the Java 21 runtime.

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
Currently, testing on Java11 and 17 are configured with "giant" gradle property `compileAndRunTestsWithJava11 ` and `compileAndRunTestsWithJava17 `. As we add one more version, we should just have a testJavaVersion separate from beamJavaVersion rather than a boolean with a giant name that sounds more complicated than it is.

This refactor will be done as part of Java 21 support

**Comment by Abacn** [comment]
Gradle 8.4 just released: https://docs.gradle.org/8.4/release-notes.html  support compile and test with Java 21 now

**Comment by Abacn** [comment]
PreCommit added: https://github.com/apache/beam/actions/runs/6709013800/job/18231112331 

mark this task as fixed for now.

There are indeed followup works, e.g.
- Complete all PostCommits when runners (e.g. Flink Spark, etc) support Java21
- #28967 Compile Java Examples Main on Java 11/17/21 when run Java Example Tests
