### ISSUE TITLE
[Bug]: testHotKeyCombineWithSideInputs permared on Spark SparkStructuredStreaming runner

### ISSUE THREAD

**Issue by Abacn** [apache/beam#29972]
### What happened?

Added in #28867. Decide either skip this test for Spark SparkStructuredStreaming VR PostCommit or fix it.

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [X] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by lostluck** [comment]
There's one week until the 2.54.0 cut and this issue is tagged for that release, if possible/necessary please complete the necessary work before then, or move this to the [2.55.0 Release Milestone](https://github.com/apache/beam/milestone/19). 

Though it sounds like we should be prepared to cherry pick a PR to skip it after the release branch is cut at least.
