### ISSUE TITLE
[prism]: unsupported feature "WindowStrategy.OutputTime" set with value (LATEST|EARLIEST)_IN_PANE

### ISSUE THREAD

**Issue by damondouglas** [apache/beam#31462]
Several Java tests fail on Prism with errors:

```
unsupported feature "WindowStrategy.OutputTime" set with value LATEST_IN_PANE
unsupported feature "WindowStrategy.OutputTime" set with value EARLIEST_IN_PANE
```

Steps to reproduce:

1. Run Prism server.

```
./gradlew :runners:prism:runServer
```

2.  Execute `:runners:portability:java:ulrLoopbackValidatesRunnerTests` on Prism:

Many tests fail with these errors, but to see the output of one quickly:

```
TEST=org.apache.beam.sdk.transforms.ReshuffleTest
./gradlew :runners:portability:java:ulrLoopbackValidatesRunnerTests -PjobEndpoint=localhost:8073 --tests="$TEST"
```

Parent tracker: #28187
Related: #31438

**Comment by lostluck** [comment]
Re-opening since the feature isn't fully implemented at this time.

https://github.com/apache/beam/blob/master/sdks/go/pkg/beam/runners/prism/internal/handlerunner.go#L343

Latest and Earliest in Pane must also take into account the rest of the Aggregation, which means using the previous computed time for the aggregation, and not simply the most recently seen timestamp for the element.

https://github.com/apache/beam/blob/master/sdks/go/pkg/beam/runners/prism/internal/handlerunner.go#L343

Assuming the aggregation struct exists `kt.time` contains the previous value during the aggregation.

https://github.com/apache/beam/blob/master/sdks/go/pkg/beam/runners/prism/internal/handlerunner.go#L350

**Comment by lostluck** [comment]
Looks like the Go SDK doesn't yet support OutputTime configuration in the windowing strategy:

#20436 tracks allowing and correctly implementing OutputTime SDK side (accounting for CombinerLifitng too).

This will be implemented and then validate via the Java tests.
